// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCId-b__n0XEmBOQa_rS9N1JhvH3_cr1nA',
    appId: '1:841844812483:web:4b05235478b3cd301bd076',
    messagingSenderId: '841844812483',
    projectId: 'rootine-9eaaf',
    authDomain: 'rootine-9eaaf.firebaseapp.com',
    storageBucket: 'rootine-9eaaf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMbRTcF8whj5t4jcqDSSBm_KBpWjT-4BE',
    appId: '1:841844812483:android:c1ba40ebad080c791bd076',
    messagingSenderId: '841844812483',
    projectId: 'rootine-9eaaf',
    storageBucket: 'rootine-9eaaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUlF7NrZPcpJPRYomVPWslfcXVPFzLCSo',
    appId: '1:841844812483:ios:a11ab8a836bf5d581bd076',
    messagingSenderId: '841844812483',
    projectId: 'rootine-9eaaf',
    storageBucket: 'rootine-9eaaf.appspot.com',
    iosBundleId: 'com.example.rootine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUlF7NrZPcpJPRYomVPWslfcXVPFzLCSo',
    appId: '1:841844812483:ios:a11ab8a836bf5d581bd076',
    messagingSenderId: '841844812483',
    projectId: 'rootine-9eaaf',
    storageBucket: 'rootine-9eaaf.appspot.com',
    iosBundleId: 'com.example.rootine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCId-b__n0XEmBOQa_rS9N1JhvH3_cr1nA',
    appId: '1:841844812483:web:b2f6e323ffb3033c1bd076',
    messagingSenderId: '841844812483',
    projectId: 'rootine-9eaaf',
    authDomain: 'rootine-9eaaf.firebaseapp.com',
    storageBucket: 'rootine-9eaaf.appspot.com',
  );

}